### ISSUE TITLE
Get a crash when attempting to take photos on a modded server. Any ideas?

### ISSUE THREAD

**Issue by KennyBurch** [andreid278/ShootIt#2]
[B#349]  [12:52:55] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Post@832dc2c:
[B#349]  java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
[B#349]  	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at java.awt.image.BufferedImage.<init>(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at com.andreid278.shootit.Renderer.CameraRenderEvents.renderCamera(CameraRenderEvents.java:129) ~[CameraRenderEvents.class:?]
[B#349]  	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_793_CameraRenderEvents_renderCamera_Post.invoke(.dynamic) ~[?:?]
[B#349]  	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
[B#349]  	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
[B#349]  	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888) [GuiIngameForge.class:?]
[B#349]  	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268) [GuiIngameForge.class:?]
[B#349]  	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133) [GuiIngameForge.class:?]
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1381) [bnz.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by andreid278** [comment]
Thank you for reporting!
Yes, it's a bug, will be fixed in the next update.
You can try to turn on a fbo in minecraft settings: go to the .minecraft folder, open options.txt and set fboEnable to true
